
-- Add source_url column to global_human_behaviors
ALTER TABLE public.global_human_behaviors ADD COLUMN source_url text;

-- Insert 15 research-backed phone engagement techniques
INSERT INTO public.global_human_behaviors (content, source_type, source_url) VALUES
('The Two-Second Rule: After the caller finishes speaking, pause for two full seconds before responding. This prevents interrupting and encourages them to elaborate further.', 'research', 'https://www.gong.io/labs/talk-to-listen-ratio/'),
('Paraphrase Before Progressing: Before moving to the next question, briefly rephrase what the caller said: "So what I''m hearing is..." This makes them feel understood and catches misunderstandings early.', 'research', 'https://www.gong.io/labs/talk-to-listen-ratio/'),
('"Tell Me More" as a Secret Weapon: When a caller shares something relevant, say "That''s interesting, tell me more" instead of immediately asking the next scripted question. This deepens engagement without feeling like an interrogation.', 'research', 'https://www.gong.io/blog/elements-of-effective-sales-conversations/'),
('Talk-to-Listen Golden Ratio: Aim to talk no more than 43% of the time and listen 57%. Top performers who close deals maintain this ratio consistently. Talking more than 65% of the call kills engagement.', 'research', 'https://www.gong.io/labs/talk-to-listen-ratio/'),
('Avoid Interrogation Mode: Do not fire questions back-to-back. Top performers ask 15-16 questions per call, not 20+. More questions does NOT mean better conversations -- it means the caller feels interrogated.', 'research', 'https://www.gong.io/blog/elements-of-effective-sales-conversations/'),
('Create Back-and-Forth Dialogue: Make the conversation feel like a coffee shop chat, not a survey. Frequently alternate between speaking and listening. Higher interactivity directly correlates with successful outcomes.', 'research', 'https://www.gong.io/blog/elements-of-effective-sales-conversations/'),
('Keep Monologues Short: Never speak for more than 25-30 seconds without pausing or checking in. Lost deals feature long seller monologues. Short bursts keep the caller engaged.', 'research', 'https://www.gong.io/blog/elements-of-effective-sales-conversations/'),
('Use Power Words Naturally: Weave in words like "imagine," "successful," and the caller''s name. Use decisive language like "definitely," "certainly," and "absolutely we can help with that." These words increase engagement and trust.', 'research', 'https://www.gong.io/blog/7-words-that-sell/'),
('Lead With Relevance, Not Pleasantries: Skip generic openers like "How are you today?" which signal a sales call. Instead, get to the point with context that proves you have something worth their time.', 'research', 'https://www.highspot.com/blog/cold-calling-techniques/'),
('Normalize Sensitive Questions: Before asking about income or personal details, add a brief normalizer: "A lot of folks I talk to aren''t sure about this one, and that''s totally fine -- just a rough ballpark works." This reduces discomfort and drop-offs.', 'research', 'https://www.leadfuze.com/how-to-build-rapport-over-the-phone/'),
('Match Their Communication Style Using NLP: If the caller speaks slowly and carefully, slow down. If they are energetic and fast, pick up your pace. Mirror their vocabulary choices -- if they say "coverage" use "coverage" not "insurance plan."', 'research', 'https://www.leadfuze.com/how-to-build-rapport-over-the-phone/'),
('Use Aizuchi Backchannels: Sprinkle in brief verbal nods while the caller is speaking: "mm-hmm," "right," "I see," "got it." This signals active listening without interrupting and is proven to build rapport faster.', 'research', 'https://www.isca-speech.org/archive/sigdial_2016/zhao16_sigdial.html'),
('Acknowledge Before Redirecting: If the caller goes off-topic or asks something you cannot answer, always acknowledge first: "That''s a really good point" or "I totally hear you on that" before redirecting. Never cut them off or ignore what they said.', 'research', 'https://clevenio.com/blog/b2b-cold-calling-tips/'),
('End With One Clear Next Step: When wrapping up or transferring, give exactly one clear action. Do not list multiple things. Say "Let me connect you with someone who can walk you through everything" -- not a paragraph of what happens next.', 'research', 'https://www.highspot.com/blog/cold-calling-techniques/'),
('Let Natural Humor Happen: If the caller makes a joke or lighthearted comment, laugh naturally and briefly engage with it before returning to the conversation. Do not force humor, but do not ignore it either. A shared laugh builds trust faster than any technique.', 'research', 'https://www.leadfuze.com/how-to-build-rapport-over-the-phone/');
